<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    public $table = 'products';
    protected $fillable = [
        'id',
        'type_id',
        'sku',
        'opera_sku',
        'old_sku',
        'override_sku',
        'name',
        'inlet',
        'outlet',
        'hose_type',
        'angle_in_deg',
        'max_Ipm',
        'voltage',
        'material',
        'bar',
        'ring_thickness',
        'diameter',
        'colour',
        'rpm',
        'status',
        'url_key',
        'visibility',
        'clearance',
        'max_temperature',
        'description',
        'short_description',
        'tech_spec_1',
        'tech_spec_2',
        'tech_spec_3',
        'product_videos',
        'nozzle_size',
        'foam_value',
        'is_featured',
        'featured_position',
        'hose_clamp_size',
        'orifice_size',
        'shoe_size',
        'thread',
        'size_and_angle',
        'inlet_outlet',
        'closing_size',
        'wheel_style',
        'flow_and_pressure',
        'country_of_manufacture',
        'select_nozzle_size',
        'dn_internal_diameter',
        'currency',
        'pack_size',
        'easy_turn',
        'priority',
        'manufacturer_number_1',
        'manufacturer_number_2',
        'manufacturer_number_3',
        'manufacturer_number_4',
        'manufacturer_number_5',
        'manufacturer_number_6',
        'manufacturer_number_7',
        'manufacturer_number_8',
        'manufacturer_number_9',
        'manufacturer_number_10',
        'hose_application',
        'hose_inlet',
        'hose_outlet',
        'hose_length',
        'hose_colour',
        'price',
        'special_price',
        'poa',
        'poa_price',
        'msrp',
        'meta_title',
        'meta_keywords',
        'meta_description',
        'pdf_title_1',
        'pdf_title_2',
        'pdf_title_3',
        'pdf_title_4',
        'categories',
        'bullet_point_1',
        'bullet_point',
    ];
}
